server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://132.232.13.117:3306/hotel
    username: root
    password: SC_bro_2019
  thymeleaf:
    prefix: classpath:/templates/
  mvc:
    static-path-pattern: /static/**
#mybatis:这几行注释掉先，不确定是否能用
#  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapper/*.xml
#  type-aliases-package: com.mybatis.springboot_mybatis.model
logging:
  level:
    com.wujingcheng7.hoteldemo_backend.mapper: debug
#registry:
#  addViewController("/index"):
#    setViewName("/hotels_display");:

# 沙箱账号
pay:
  alipay:
    gatewayUrl: https://openhome.alipay.com/gateway.do
    appid: 2019080566129054
    appPrivateKey:
    alipayPublicKey:
    returnUrl:
    notifyUrl:


